apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multitool-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: multitool-storage
              mountPath: /mnt/data
      volumes:
        - name: multitool-storage
          persistentVolumeClaim:
            claimName: multitool-pvc